### ISSUE TITLE
Pulling location data via external JSON URL?

### ISSUE THREAD

**Issue by aaronbushnell** [eschwartz/backbone.googlemaps#38]
What's the recommended way to pull in an external JSON URL as the location data? I've been having some trouble getting my head around how to do this. :confused:

**Comment by eschwartz** [comment]
This library binds markers to [Location](https://github.com/eschwartz/backbone.googlemaps/blob/master/lib/backbone.googlemaps.js#L28) and [LocationCollection](https://github.com/eschwartz/backbone.googlemaps/blob/master/lib/backbone.googlemaps.js#L74) objects. You should be able to extend either of these objects to sync up with an API server.

Note that the data you receive must be restructured into a format that the location model expects: 
```
{
  lat: int
  lng: int
  selected: ?boolean
  title: ?string
}
```

You can use [`parse`](http://backbonejs.org/#Collection-parse) to normalize the input data. Or you could use some kind of [Backbone View Model extension](https://github.com/tommyh/backbone-view-model).

You could also take a look at what I'm calling the "new" version of this library, which is [Aeris.js](https://github.com/aerisweather/aerisjs). See [my note about it here](https://github.com/eschwartz/backbone.googlemaps#a-note-regarding-the-future-of-backbonegooglemaps). The aeris `MarkerCollection` object has built in support for view model transformations, and is generally more flexible (and better supported).

**Comment by aaronbushnell** [comment]
Thanks for the quick update. I'll check into some of these options!
